
development:
  adapter: postgresql
  encoding: unicode
  database: lunch_lady
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: lunch_lady_test
  pool: 5
  username: 
  password: 


production:
  adapter: postgresql
